apiVersion: charts.helm.k8s.io/v1alpha1
kind: Turbodif
metadata:
  name: turbodif-release
spec:
  # Default values copied from <project_dir>/helm-charts/turbodif/values.yaml

  # Default values for turbodif.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # Turbo server version and address
  serverMeta:
    version: 8.0
    turboServer: https://Turbo_server_URL

  # Turbonomic server api user and password
  # The opsManagerUserName requires Turbo administrator role
  #restAPIConfig:
    #turbonomicCredentialsSecretName: "turbonomic-credentials"
    #opsManagerUserName: Turbo_username
    #opsManagerPassword: Turbo_password

  # Specify a unique suffix to the DataIngestionFramework target type
  # The Target Type will appear as DataIngestionFramework-<targetTypeSuffix> on the UI
  # Do not specify Turbonomic as the targetTypeSuffix, it is reserved for internal use
  #targetTypeSuffix: CustomMetricSource

  #targetConfig:
    #keepStandalone: false

  #args:
    # logging level
    #logginglevel: 2
